### ISSUE TITLE
Setting Kanban Board

### ISSUE THREAD

**Issue by yigitm** [yigitm/recipe-app#9]
Project Collaborators: 2
Project Link: https://github.com/yigitm/recipe-app/projects/1

We created the Kanban boards with the necessary cards base on the project requirements.

Thank you for your time.

**Comment by FrederickMih** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted an issue link without the following information in your summary:** 
:fast_forward: A link to the GitHub project,
:fast_forward: Information about the number of people in your group.

 **NB**: Please note that **we** is not a number. It should be a number ie 2, 3........

Kindly update your summary and submit your project once more.

Wish you all the best :pray: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by yigitm** [comment]
Thank you. I changed this informations.

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @yigitm  and @disc3110, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job setting up you kanban board
- Your task were split fairly

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
